version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/y-yagi/tomato

    steps:
      - checkout
      - run:
          name : Run dep
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Run vet
          command: go vet
      - run:
          name: Run lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status
      - run:
          name: Run staticcheck
          command: |
            go get -u honnef.co/go/tools/cmd/staticcheck
            staticcheck
      - run:
          name: Run tests
          command: go test -v
  dep-update:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/y-yagi/tomato

    steps:
      - checkout
      - run:
          name: Run ci-dep-update
          command: |
            go get -d github.com/y-yagi/ci-dep-update
            cd $GOPATH/src/github.com/y-yagi/ci-dep-update
            dep ensure -vendor-only
            go install
            cd /go/src/github.com/y-yagi/tomato
            ci-dep-update -u y-yagi -r y-yagi/tomato

workflows:
  version: 2
  build:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 22 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - dep-update
